apiVersion: v1
kind: Service
metadata:
  name: {{ include "TMC.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "TMC.name" . }}
    helm.sh/chart: {{ include "TMC.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.ClusterIP }}
  clusterIP: {{ .Values.service.ClusterIP }} #just for test purpose
    port: 123  #just for test purpose
  {{- end }}
  ports:
  - name: tmc-port
    port: {{ .Values.service.port }}
    {{- if .Values.service.nodePort }}
    type: nodePort
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "TMC.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
