apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "TMC.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "TMC.name" . }}
    helm.sh/chart: {{ include "TMC.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "TMC.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "TMC.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: TMS_DEFAULTURL
            value: "terracotta://localhost:9410"
          ports:
            - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: {{ .Values.spec.template.spec.containers.volumeMounts.name }}
          mountPath: {{ .Values.spec.template.spec.containers.volumeMounts.mountPath }}
      volumes:
        - name: {{ .Values.spec.template.spec.volumes.name }}
          hostPath:
            path: {{ .Values.spec.template.spec.volumes.hostPath.path }}