# Default values for TMC.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: terracotta-tmc
service:
  type: NodePort
  port: 9480
replicaCount: 1

image:
  repository: store/softwareag/tmc
  tag: 10.3
  pullPolicy: Always

spec:
  template:
    spec:
      containers:
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: TMS_DEFAULTURL
          value: "terracotta://localhost:9410"
        volumeMounts:
            name: tmcdata
            mountPath: /data/tmc/
      volumes:
         name: tmcdata
         hostPath: 
          path: /home/docker/tmcdata